name: DynamicMTML Pack
id:   DynamicMTML
key:  dynamicmtml
author_name: Alfasado Inc.
author_link: http://alfasado.net/
pack_link: https://github.com/movabletype/DynamicMTML
version: 1.63
schema_version: 1.02
l10n_class: DynamicMTML::L10N
init_request: >
    sub {
        my $app = MT->instance;
        my $ua = $app->get_header( 'User-Agent' );
        unless ( ref $app eq 'MT::App::CMS' ) {
            if ( $ua =~ /\ADoCoMo\/2\.0 /i ) {
                $app->{ response_content_type } = 'application/xhtml+xml';
            }
        }
    }
config_settings:
    DynamicForceCompile:
        default: 0
        updatable: 1
    DisableCompilerWarnings:
        default: 0
        updatable: 1
    UserSessionTimeoutNoCheck:
        default: 0
        updatable: 1
    DynamicSiteBootstrapper:
        default: .mtview.php
        updatable: 1
    DynamicIncludeStatic:
        default: 0
        updatable: 1
    AllowMagicQuotesGPC:
        default: 0
        updatable: 1
    DynamicPHPFirst:
        default: 0
        updatable: 1
    PermCheckAtPreview:
        default: 0
        updatable: 1
    AllowableTags:
        default: '<a><br><b><i><p><strong><em><img><ul><ol><li><blockquote><pre>'
        updatable: 1
object_types:
    blog:
        dynamic_mtml: boolean
        dynamic_cache: boolean
        dynamic_conditional: boolean
        search_cache: boolean
        search_conditional: boolean
        search_cache_expiration: string(25)
        dynamic_extension: string(255)
        exclude_extension: string(255)
        index_files: string(255)
applications:
    cms:
        menus:
            tools:clear_cache:
                label: Flush Dynamic Cache
                order: 1950
                mode: flush_dynamic_cache
                condition: $dynamicmtml::DynamicMTML::CMS::_dynamic_permission
                view:
                    - blog
                    - website
                    - system
        methods:
            install_dynamic_mtml: $dynamicmtml::DynamicMTML::CMS::_install_dynamic_mtml
            flush_dynamic_cache: $dynamicmtml::DynamicMTML::CMS::_flush_dynamic_cache
callbacks:
    MT::App::CMS::template_source.list_template: $dynamicmtml::DynamicMTML::Plugin::_list_template_source
    MT::App::CMS::template_param.list_template: $dynamicmtml::DynamicMTML::Plugin::_list_template_param
    MT::App::CMS::template_param.cfg_prefs: $dynamicmtml::DynamicMTML::Plugin::_cfg_prefs_param
    MT::App::CMS::template_source.cfg_prefs: $dynamicmtml::DynamicMTML::Plugin::_cfg_prefs_source
    MT::App::CMS::template_source.footer: $dynamicmtml::DynamicMTML::Plugin::_footer_source
    MT::App::CMS::template_param.edit_template: $dynamicmtml::DynamicMTML::Plugin::_edit_template_param
    build_file: $dynamicmtml::DynamicMTML::Plugin::_build_file
    build_page: $dynamicmtml::DynamicMTML::Plugin::_build_page
    build_file_filter: $dynamicmtml::DynamicMTML::Plugin::_build_file_filter
    build_dynamic: $dynamicmtml::DynamicMTML::Plugin::_build_dynamic
    cms_post_save.blog:
        - handler: $dynamicmtml::DynamicMTML::Plugin::_post_save_blog
          priority: 10
        - handler: $dynamicmtml::DynamicMTML::Plugin::_disable_dynamicmtml
          priority: 1
    cms_post_save.template: $dynamicmtml::DynamicMTML::Plugin::_post_save_template
    MT::App::CMS::template_param.view_log: $dynamicmtml::DynamicMTML::Plugin::_view_log
    MT::App::CMS::template_param: $dynamicmtml::DynamicMTML::Plugin::_cb_tp
tags:
    block:
        RawMTML: $dynamicmtml::DynamicMTML::Tags::_hdlr_raw_mtml
        CommentOut: $dynamicmtml::DynamicMTML::Tags::_hdlr_comment_out
        CommentStrip: $dynamicmtml::DynamicMTML::Tags::_hdlr_comment_strip
        LoginAuthorCtx: $dynamicmtml::DynamicMTML::Tags::_hdlr_login_author_ctx
        ClientAuthorBlock: $dynamicmtml::DynamicMTML::Tags::_hdlr_login_author_ctx
        SearchEntries: $dynamicmtml::DynamicMTML::Tags::_hdlr_search_entries
        QueryLoop: $dynamicmtml::DynamicMTML::Tags::_hdlr_query_loop
        SetQueryVars: $dynamicmtml::DynamicMTML::Tags::_hdlr_set_query_vars
        QueryVars: $dynamicmtml::DynamicMTML::Tags::_hdlr_query_vars
        SplitVars: $dynamicmtml::DynamicMTML::Tags::_hdlr_splitvars
        IfLogin?: $dynamicmtml::DynamicMTML::Tags::_hdlr_if_login
        IfUserHasPermission?: $dynamicmtml::DynamicMTML::Tags::_hdlr_if_user_has_permission
        IfUserAgent?: $dynamicmtml::DynamicMTML::Tags::_hdlr_user_agent
        IfBlogDynamicCache?: $dynamicmtml::DynamicMTML::Tags::_hdlr_if_dynamic_cache
        IfBlogDynamicConditional?: $dynamicmtml::DynamicMTML::Tags::_hdlr_if_dynamic_conditional
        ReferralKeywords: $dynamicmtml::DynamicMTML::Tags::_hdlr_referralkeywords
        DynamicMTML: $dynamicmtml::DynamicMTML::Tags::_hdlr_dynamicmtml
        NonDynamicMTML: $dynamicmtml::DynamicMTML::Tags::_hdlr_nondynamicmtml
        IfBlogDynamicMTML?: $dynamicmtml::DynamicMTML::Tags::_hdlr_if_blog_dynamicmtml
        EntryCategoryBlock: $dynamicmtml::DynamicMTML::Tags::_hdlr_entry_category_block
        BuildRecurs: $dynamicmtml::DynamicMTML::Tags::_hdlr_build_recurs
        SetErrorHandler: $dynamicmtml::DynamicMTML::Tags::_hdlr_set_error
        StripTags: $dynamicmtml::DynamicMTML::Tags::_hdlr_strip_tags
    function:
        ML: $dynamicmtml::DynamicMTML::Tags::_hdlr_raw_mtml_tag
        MTML: $dynamicmtml::DynamicMTML::Tags::_hdlr_raw_mtml_tag
        RawMTMLTag: $dynamicmtml::DynamicMTML::Tags::_hdlr_raw_mtml_tag
        BlogDynamicCache: $dynamicmtml::DynamicMTML::Tags::_hdlr_dynamic_cache
        BlogDynamicConditional: $dynamicmtml::DynamicMTML::Tags::_hdlr_dynamic_conditional
        BlogDynamicSearchCache: $dynamicmtml::DynamicMTML::Tags::_hdlr_dynamic_search_cache
        BlogDynamicSearchConditional: $dynamicmtml::DynamicMTML::Tags::_hdlr_dynamic_search_conditional
        BlogDynamicMTMLCache: $dynamicmtml::DynamicMTML::Tags::_hdlr_dynamic_search_cache
        BlogDynamicMTMLConditional: $dynamicmtml::DynamicMTML::Tags::_hdlr_dynamic_search_conditional
        BlogDynamicSearchCacheExpiration: $dynamicmtml::DynamicMTML::Tags::_hdlr_dynamic_search_cache_expiration
        BlogDynamicDirectoryIndex: $dynamicmtml::DynamicMTML::Tags::_hdlr_dynamic_directory_index
        BlogDynamicExtension: $dynamicmtml::DynamicMTML::Tags::_hdlr_dynamic_extension
        BlogDynamicExcludeExtension: $dynamicmtml::DynamicMTML::Tags::_hdlr_dynamic_exclude_extension
        BlogFilesMatchDirective: $dynamicmtml::DynamicMTML::Tags::_hdlr_blog_files_match_directive
        BlogFilesDirective: $dynamicmtml::DynamicMTML::Tags::_hdlr_blog_files_directive
        BlogFilesMatch: $dynamicmtml::DynamicMTML::Tags::_hdlr_blog_files_match
        CurrentArchiveURL: $dynamicmtml::DynamicMTML::Tags::_hdlr_current_archive_url
        CurrentArchiveFile: $dynamicmtml::DynamicMTML::Tags::_hdlr_current_archive_file
        TableColumnValue: $dynamicmtml::DynamicMTML::Tags::_hdlr_table_column_value
        Query: $dynamicmtml::DynamicMTML::Tags::_hdlr_query
        UserAgent: $dynamicmtml::DynamicMTML::Tags::_hdlr_user_agent
        PluginPath: $dynamicmtml::DynamicMTML::Tags::_hdlr_plugin_path
        PowerCMSFilesDir: $dynamicmtml::DynamicMTML::Tags::_hdlr_powercms_files_dir
        ReferralKeyword: $dynamicmtml::DynamicMTML::Tags::_hdlr_referralkeyword
        Trans: $dynamicmtml::DynamicMTML::Tags::_hdlr_trans
        EntryStatusInt: $dynamicmtml::DynamicMTML::Tags::_hdlr_entry_statusint
        AuthorLanguage: $dynamicmtml::DynamicMTML::Tags::_hdlr_author_language
        DynamicSiteBootstrapper: $dynamicmtml::DynamicMTML::Tags::_hdlr_dynamic_site_bootstrapper
        FileGetContents: $dynamicmtml::DynamicMTML::Tags::_hdlr_file_get_contents
        PluginVersion: $dynamicmtml::DynamicMTML::Tags::_hdlr_plugin_version
        Rand: $dynamicmtml::DynamicMTML::Tags::_hdlr_rand
        Error: $dynamicmtml::DynamicMTML::Tags::_hdlr_error
    modifier:
        pickup_extension: $dynamicmtml::DynamicMTML::Tags::_filter_pickup_extension
        highlightingsearchword: $dynamicmtml::DynamicMTML::Tags::_filter_highlightingsearchword
        build_mtml: $dynamicmtml::DynamicMTML::Tags::_filter_build_mtml
        make_seo_basename: $dynamicmtml::DynamicMTML::Tags::_filter_make_seo_basename
        intval: $dynamicmtml::DynamicMTML::Tags::_filter_intval
        trimwhitespace: $dynamicmtml::DynamicMTML::Tags::_filter_trimwhitespace
